### PR TITLE
Added bin

### PR DESCRIPTION
**Pull request by minecraftmuse3**
Added the bin

### CODE REVIEW

**Comment by malucard** [comment]
Cool :)

**Comment by minecraftmuse3** [comment]
Let's hope he merges it :)

**Comment by malucard** [comment]
*they :)

**Comment by byteandahalf** [comment]
I'll merge it if you fix all that horrible indenting.

**Comment by minecraftmuse3** [comment]
Ok lol

**Comment by minecraftmuse3** [comment]
I just added the lamp, so close this pull request and I'll make another with the indenting fixed.

**Pull request closed without merging**
