### PR TITLE
Allow Doorbell to be rotated

### PR DESCRIPTION
**Pull request by malucard**
Untested though

### CODE REVIEW

**Comment by malucard** [comment]
@RedstoneGunMade What, breaking furniture or activating doorbells?

**Comment by byteandahalf** [comment]
This will need to be changed, since doorbell goes by what side you click on. But it works for now.

**Comment by malucard** [comment]
I have an idea for rotationType, will implement that later

**Comment by malucard** [comment]
Currently, I'm focusing in adding stuff (principally kitchen stuff, I love kitchen stuff!)

**Comment by malucard** [comment]
I've already added Toaster, Chopping Board, Blender and Microwave :D

**Pull request merged**
