### PR TITLE
Add Plate and the Oven renderer from PC

### PR DESCRIPTION
**Pull request by malucard**
Also updated to the new texture system

### CODE REVIEW

**Comment by MrCrayfish** [comment]
This will need updating for the latest branch for it to be merged

**Comment by malucard** [comment]
"Latest branch"?

**Comment by malucard** [comment]
Anyways, it is already updated

**Comment by minecraftmuse3** [comment]
Just out of interest, WHY ISNT THIS MERGED @jv110 @MrCrayfish @byteandahalf

**Pull request merged**
