### PR TITLE
Fixed Lots Of Oven/CookieJar Errors/Renders

### PR DESCRIPTION
**Pull request by bia5**
It Works!

### CODE REVIEW

**Comment by trashfloozy** [comment]
._. If render pass makes glass see through I will be very happy.

**Comment by malucard** [comment]
you forgot to init()

**Comment by bia5** [comment]
@jv110 Done

**Comment by MrCrayfish** [comment]
Can someone confirm that the glass does not render black? Also any means necessary of calling "init()" because it has not been used in previous Tile initializations?

**Comment by skullkeeper94** [comment]
IDK HOW I DID IT BUT I DID!!!
screenshot_2015-07-25-21-52-32

**Comment by skullkeeper94** [comment]
I'm using a texture pack, sorry.

**Comment by skullkeeper94** [comment]
The thing is that I did this when I was going through the files... I'm adding another block (needs GUI)

**Comment by trashfloozy** [comment]
@MrCrayfish I fixed it... 
screenshot_2015-07-25-21-52-32

**Comment by brk1864** [comment]
@skullkeeper94  where is fixed version ? I cant see it on your account

**Comment by trashfloozy** [comment]
@brk1864 I didn't add it since I'm adding two blocks (Package and TV)

**Comment by trashfloozy** [comment]
@brk1864 there I added it. It was a misprint in Furniture_hooks.cpp

**Comment by brk1864** [comment]
Okey.You are good at programming.Mrcrayfish dont care MCPE.

**Comment by brk1864** [comment]
@skullkeeper94  but there is bugs.i cant compile it

**Comment by bia5** [comment]
And @MrCrayfish idk, i dont think we need it for them, let me check.

**Comment by malucard** [comment]
@MrCrayfish yes, init() removes the X-Ray effect and fixes lighting. Also doing
Tile::solid[id] = false;
Tile::lightBlock[id] = 0;
is a good idea.

**Comment by malucard** [comment]
To fix the black glass problem you should add
renderPass = Tile::glass->renderPass;

**Comment by malucard** [comment]
lol everything I said was added

**Pull request closed without merging**
