### PR TITLE
Added Oven and Cookie Jar

### PR DESCRIPTION
**Pull request by bia5**
The only thing thats wrong, (that I belive), is the glass on the Cookie Jar. Other than that its bugless!

### CODE REVIEW

**Comment by malucard** [comment]
Just a tip, use "Add" instead of "Added", idk why but it looks better

**Comment by bia5** [comment]
@jv110 lol XD

**Comment by RandomAltThing** [comment]
@Crazywolf23 Please remove the "origonal" ("original" xD) then make this PR again.

**Comment by bia5** [comment]
Done

**Comment by Koolman12** [comment]
Send the apk plz

**Comment by bia5** [comment]
@Koolman12 in about an hour ;)

**Comment by Koolman12** [comment]
send it now

**Comment by Koolman12** [comment]
plz

**Comment by Koolman12** [comment]
Dude

**Comment by RandomAltThing** [comment]
@Koolman12 Stop spamming the Pull Requests it has been merged. If you continue to spam @MrCrayFish may or may not block you depending on how busy he is.

**Pull request merged**
