### PR TITLE
Add Cabinet

### PR DESCRIPTION
**Pull request by malucard**
Added a Cabinet Tile

### CODE REVIEW

**Comment by byteandahalf** [comment]
Pretty cool, but with all the refactoring coming all this code will be destroyed. Can you recreate it after we rewrite the code?

**Comment by malucard** [comment]
Ok

**Comment by MrCrayfish** [comment]
I'll leave the PR open, just update it to match the code once it's refactored

**Comment by byteandahalf** [comment]
Then he can just start a new PR?

**Comment by MrCrayfish** [comment]
He could have just modified this PR to suit the new code.

**Comment by malucard** [comment]
So... Is refactoring done?

**Pull request closed without merging**
