### PR TITLE
patch 2

### PR DESCRIPTION
**Pull request by trashfloozy**
Here it is: The mini-bug fixes AND a the Bedside Cabinet was added. Also how do I make the block behind, beside, and in front of the Bedside Cabinet not make that side disappear?

### CODE REVIEW

**Comment by malucard** [comment]
You need to init() the block, and apparently no FurniturePE block does init() lol

**Comment by trashfloozy** [comment]
@jv110  ._. OK. Do you know how to add the crafting recipe?

**Comment by bia5** [comment]
@skullkeeper94 I pretty sure only 3 people now how to add crafting

**Comment by trashfloozy** [comment]
@CrazyWolf23 WHO??? I'm starting to get annoyed with myself..

**Comment by malucard** [comment]
@skullkeeper94 me, @mackthehobbit and @byteandahalf

**Comment by trashfloozy** [comment]
@jv110 please tell me. Imma go insane :(

**Comment by mackthehobbit** [comment]
@jv110 @skullkeeper94 If you need examples of crafting recipes, you should take a look at my Gists: https://gist.github.com/mackthehobbit

**Comment by trashfloozy** [comment]
@mackthehobbit well, I'm going to go hibernate for a year trying to understand this. XD

**Comment by malucard** [comment]
@skullkeeper94 but if you're hibernating, you can't read it

**Comment by bia5** [comment]
Lol

**Comment by trashfloozy** [comment]
@jv110 XD lol

**Comment by trashfloozy** [comment]
@mackthehobbit Wait, do I only need those two files or do I need more?

**Comment by trashfloozy** [comment]
(Closing this pull request)

**Pull request closed without merging**
