### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by trashfloozy**
Everything should be fixed to everyone who tries to compile it. IDK how to fix glass being black and why the block behind, in front, and next to Bedside Cabinet disappear. (BEDSIDE CABINET NOT IN CODE)

### CODE REVIEW

**Comment by MrCrayfish** [comment]
What exactly did this fix for the compiling? All I see is a change to the bounding box and render.

**Comment by trashfloozy** [comment]
Oh, there's a part in OvenTile.cpp where if you try compiling it gives you an error (really easy to fix). But the obsidian was just a render bug.

**Comment by trashfloozy** [comment]
:) hope you add this.

**Comment by trashfloozy** [comment]
Also I'm adding a Bedside Cabinet :3

**Pull request closed without merging**
