### PR TITLE
Fixed TV

### PR DESCRIPTION
**Pull request by minecraftmuse3**
Fixed skullkeepers tv :)

### CODE REVIEW

**Comment by minecraftmuse3** [comment]
Ok, I just renamed the entire library from tile to block. Commit incoming.

**Comment by MrCrayfish** [comment]
WIll merge once I get that rename commit!

**Comment by minecraftmuse3** [comment]
Done ;). That took about 3 hours lol :)

**Comment by minecraftmuse3** [comment]
Think I'm gonna do the computer and printer next

**Comment by MrCrayfish** [comment]
Great work man. I appreciate it a lot. Just noticed you left printer.json in the renders, get that out and will merge :P

**Comment by minecraftmuse3** [comment]
All good now :). And no problem!

**Comment by MrCrayfish** [comment]
Merged. Thank you for your contributions!

**Comment by MrCrayfish** [comment]
Also before you commit anymore, you are missing author information.

**Comment by minecraftmuse3** [comment]
@MrCrayfish how do I fix that?

**Comment by MrCrayfish** [comment]
What are you using to commit? If you are using the GitHub app, make sure your details are entered in.

**Pull request merged**
