### PR TITLE
Add some kitchen stuff

### PR DESCRIPTION
**Pull request by malucard**
Rendering code copied directly from PC!

### CODE REVIEW

**Comment by minecraftmuse3** [comment]
Ha ha I'll send through a pull request to your fork with the answer

**Comment by minecraftmuse3** [comment]
I opened a pull request onto your forked repo with the textures added properly :)

**Comment by ghost** [comment]
@jv110 how to get this commit for test it?

**Comment by minecraftmuse3** [comment]
@RedstoneGunMade Get it from jv100-master

**Comment by malucard** [comment]
I'm so bad at counter rendering

**Comment by ghost** [comment]
@jv110 Can you fix item textures? Most of new items (less knife) have the same item texture

**Comment by malucard** [comment]
Yeah, its because the 'record' textures ended, but @minecraftmuse3 came with a solution, implementing it :)

**Comment by ghost** [comment]
Ok ;)
Can you give me your twitter? I have a thing that might you want ;)

**Comment by malucard** [comment]
I'm @jv110br_ on twitter ;)

**Comment by ghost** [comment]
ok Thx!

**Comment by ghost** [comment]
@jv110 Not works now! (not compiles)

**Pull request merged**
