### PR TITLE
Added Cabinet, Doorbell and fixed item textures

### PR DESCRIPTION
**Pull request by malucard**

### CODE REVIEW

**Comment by ghost** [comment]
@jv110 When you fix it for put flower pot?

**Comment by malucard** [comment]
Dude flower pot is not part of Furniture Mod!!!!!!!111!!1!!1!1111!1!1!1!1!!111111!!!!!!!1!1!1!111111!!!11!!!!!!1111

**Comment by ghost** [comment]
ok xD

**Comment by byteandahalf** [comment]
Thanks for your contribution. I need to fix a few things with it, but it is overall much appreciated.

**Pull request merged**
