### PR TITLE
Added Kitchen Cabinet

### PR DESCRIPTION
**Pull request by RandomAltThing**
(TheDiamondYT is my username for git)

This adds the Kitchen Cabinet from the PC mod. The item is currently an apple untill I find the texture.

### CODE REVIEW

**Comment by RandomAltThing** [comment]
Hello? @MrCrayFish @jv110

**Comment by Koolman12** [comment]
Can u make an apk

**Comment by RandomAltThing** [comment]
@MrCrayFish @Byteandahalf Can I continue adding blocks? I am willing to add them all if you actually come on once in a while and merge the pull requests. I may ask @Jv110 for help with rendering.

**Comment by Koolman12** [comment]
srsly can u make an apk

**Comment by jv110** [comment]
@Koolman12 no

**Comment by jv110** [comment]
@RandomAltThing Why ask me? I just copy from PC version lel

**Comment by RandomAltThing** [comment]
@jv110  I just copy existing blocks rendering lol that's why I used <code>new CabinetRenderer()</code>

**Comment by Koolman12** [comment]
NOOOOOO

**Comment by RandomAltThing** [comment]
Finally :D deleting branch so I can implement more

**Pull request merged**
