### PR TITLE
Added oven

### PR DESCRIPTION
**Pull request by minecraftmuse3**
Don't worry, the indenting' s good :)

### CODE REVIEW

**Comment by malucard** [comment]
Noooo!!!!!!!!!!!!!!!!!!!!!!!11

**Comment by malucard** [comment]
I mean, I was gonna add all kitchen stuff at the same time (progress: Toaster, Microwave, Chopping Board, Blender)

**Comment by malucard** [comment]
The only problem is that this overrides my changes

**Comment by malucard** [comment]
Why did you add spaces before some things? That kills the indenting

**Comment by minecraftmuse3** [comment]
What things?

**Comment by minecraftmuse3** [comment]
If it really bothers you so much...

**Comment by malucard** [comment]
nah it doesnt

**Comment by malucard** [comment]
image

all this good stuff :D

**Comment by minecraftmuse3** [comment]
:)

**Comment by byteandahalf** [comment]
Sorry, I'm going to let @jv110 work on kitchen stuff. Plus, you need to work on that indenting.

**Comment by minecraftmuse3** [comment]
Okay :). What can I do? Bathroom stuff? Garden stuff?

**Comment by malucard** [comment]
Anything you want

**Pull request closed without merging**
