### PR TITLE
Added lamp and bin

### PR DESCRIPTION
**Pull request by minecraftmuse3**

### CODE REVIEW

**Comment by minecraftmuse3** [comment]
The indenting isn't working for me. It keeps lagging and putting it in the wrong place

**Comment by malucard** [comment]
You could just edit the previous pull request.

**Comment by minecraftmuse3** [comment]
Done

**Comment by byteandahalf** [comment]
You'll need to update this to my newest commit

**Comment by minecraftmuse3** [comment]
Okay. Be a sec...

**Comment by minecraftmuse3** [comment]
Done

**Comment by minecraftmuse3** [comment]
Merge it now. Btw, @byteandahalf, you did a great job with the painting! It works great :D

**Comment by minecraftmuse3** [comment]
Whoops accidentally closed it D:

**Pull request closed without merging**
