### PR TITLE
Added Oven

### PR DESCRIPTION
**Pull request by bia5**
I Added an oven but i cant upload images, also there is a placing bug that the block faces the wrong way, but other than that, the rendering and shapes are just like the pc edition.

### CODE REVIEW

**Comment by bia5** [comment]
@byteandahalf @MrCrayfish  @jv110 Sorry For Adding The Bugs, But It Still Builds Though, IJust Figured That Adding The Oven Would Help. Thanks For Reading.

**Comment by minecraftmuse3** [comment]
I already tried this, and it got rejected because @jv110 is doing all of the kitchen stuff.

**Comment by minecraftmuse3** [comment]
Plus, your indenting is all wrong (Not that I can say much!!!)

**Comment by bia5** [comment]
Oh ok, hey @minecraftmuse3 wants work together to add the living room stuff, like couches, curtains, and bedside tables?

**Comment by bia5** [comment]
Lol whoops acsidently closed the request, lol

**Comment by ghost** [comment]
hi!

**Comment by ghost** [comment]
@CrazyWolf23 you have twitter?

**Comment by bia5** [comment]
Yes @CrazyWolf23_YT_

**Comment by bia5** [comment]
@RedstoneGunMade lol forgot to "@" you lol. And ask if you like the look of the oven.

**Comment by ghost** [comment]
ok wait @CrazyWolf23 ;)

**Comment by ghost** [comment]
@CrazyWolf23 you can follow me in twitter? i have to send a private message for you ;)

**Comment by malucard** [comment]
I suggest you use a Git client next time.

**Comment by bia5** [comment]
@jv110 what's that?

**Comment by malucard** [comment]
@CrazyWolf23 I thought all people know about Git clients, it's interesting to know someone who doesn't even know whats one

**Comment by malucard** [comment]
@CrazyWolf23 They're just apps to use Git with. It's sooooooooooooooooooooooooooooooooooooooo shitty to work on the GitHub website

**Comment by bia5** [comment]
Ok

**Comment by bia5** [comment]
@byteandahalf can you please look at what i added, Im Going to work on counter tops next if thats ok.

**Comment by minecraftmuse3** [comment]
Yeah @jv110

**Comment by bia5** [comment]
@minecraftmuse3 wana work together?

**Comment by minecraftmuse3** [comment]
Ok @CrazyWolf23

**Comment by Koolman12** [comment]
Can i Beta test the oven update???????

**Comment by bia5** [comment]
@Koolman12 yes, but there is one bug where the oven rotates wrong, download it at https://github.com/CrazyWolf23/MrCrayfishFurnitureMod-StillTesting

**Comment by Koolman12** [comment]
Thanks Bro

**Comment by Koolman12** [comment]
How do i download?

**Comment by Koolman12** [comment]
CrazyWolf23 Plz tell me how i download

**Comment by bia5** [comment]
@Koolman12 go to https://github.com/CrazyWolf23/MrCrayfishFurnitureMod-StillTesting and scroll down till you see the "download zip" button, and that's how you download the zip, if you want me to I can make an apk (that can be decompiled) so you don't have to use aide.

**Comment by Koolman12** [comment]
How long will it take to make an apk??

**Comment by Koolman12** [comment]
Make an apk

**Comment by bia5** [comment]
Here is the download link of my version of the addon: https://www.dropbox.com/s/ocaujfeouwqx5s5/MrCrayfishFurnitureMod-StillTesting-master.apk?dl=1

**Comment by Koolman12** [comment]
Bro can u make a Flans car mod for MCPE??

**Comment by Koolman12** [comment]
Btw nice youtube videos i sub:)

**Comment by bia5** [comment]
@Koolman12 1, yes I'll start on the mod/addon in a few days, 2, thanks for subscribing.

**Comment by Koolman12** [comment]
:)

**Comment by Koolman12** [comment]
Btw bro can u try and add computer and printer by tomorrow plz try

**Comment by bia5** [comment]
@Koolman12 I can add the blocks but not the functions. But I'll try and add them by tomorrow.

**Comment by bia5** [comment]
Oooooooo, nothing is wrong with my additions now, yay!

**Comment by minecraftmuse3** [comment]
You've overridden all of @jv110 's commits with kitchen stuff

**Comment by bia5** [comment]
@minecraftmuse3 what do you mean

**Comment by ghost** [comment]
@CrazyWolf23 you can talk with me now? In twitter

**Comment by bia5** [comment]
@RedstoneGunMade ok

**Comment by minecraftmuse3** [comment]
His other pull request adding heaps of kitchen stuff; Your pull request has none of that.

**Comment by Koolman12** [comment]
@CrazyWolf23 Send me the link tomorrow at 12.00

**Comment by Koolman12** [comment]
12:00

**Comment by Koolman12** [comment]
@CrazyWolf23

**Comment by minecraftmuse3** [comment]
@Koolman12 Why do you expect him to drop whatever he is doing so he can come and help you? It's really not hard to make it an apk :-1:

**Comment by Koolman12** [comment]
Me and Him are Friends and I subscribe to him

**Comment by bia5** [comment]
@Koolman12 Sorry, i was doing school, ill update the addon to jv110s version then ill send you an apk

**Comment by bia5** [comment]
@Koolman12 Here Is The Updated Apk: https://www.dropbox.com/s/pu5nx5yn413pnl5/Mr.Crayfish%60sFurnitureMod.apk?dl=1
I`ll start working on the computer and printer soon, i have to do somthing for @RedstoneGunMade

**Comment by Koolman12** [comment]
Ok

**Comment by MrCrayfish** [comment]
Closing this pull request. It's no longer needed.

**Pull request closed without merging**
